### ISSUE TITLE
Add to Missions Development: "Short Description"

### ISSUE THREAD

**Issue by ALRubinger** [fabric8-launcher/launcher-documentation#979] opened 2018-01-02 19:45 UTC
We'll need a "Short Description" one liner field to briefly describe what each mission is about.  Add to the new Missions template and fill in for all Missions docs, as well as add into the catalog metadata as necessary.

**Comment by edewit** [comment] 2018-01-04 10:37
@ALRubinger is this an duplicate of this issue: https://github.com/fabric8-launcher/launcher-planning/issues/74

**Comment by tradej** [comment] 2018-01-08 11:45
In case it is not, can you please elaborate what sort of description you are looking for and where exactly this information should be in the documentation? We have sort of one-paragraph descriptions in the docs already, so I am worried about content duplication.

**Comment by lavernw1** [comment] 2018-01-10 16:16
@ALRubinger  Just an update. In issue [777 ](https://github.com/fabric8-launcher/launcher-documentation/issues/777) we renamed the ConfigMap Mission to "Externalized Configuration" to better match other documentation and for clarity for users.  Will this change need to be made in the catalog descriptions as well.

**Comment by rhoads-zach** [comment] 2018-01-15 16:13
moved here: https://issues.jboss.org/browse/RHOARDOC-1109

**Closed by rhoads-zach** 2018-01-15 16:13 UTC
Labels: Mission | CRUD, Mission | Circuit Breaker, Mission | ConfigMap, Mission | Health Check, Mission | REST API, Mission | SSO, Type | Enhancement
